DO_RECALL_ATTEMPT = True
DO_MERGE_ATTEMPT = False
DO_NOISE_SINGLE_CLUSTER = False

similarity_threshold = 0.88 # Cluster
MERCLUSTER_SIM_GATE = 0.8   # filter_noise_by_similarity
DENOISE_SIM_GATE = 0.7      # recall_unit

MISS_SHOT_P = 0.6

ADJ_RANGE = 180
MERGE_ATTEMPT_ADJ_RANGE = ADJ_RANGE / 2
TM_GAP_GATE = 720
MERGE_CLUSTER_ADJ_RANGE = 300

workers = 64
ORDINARY_NOISE = 1
STRONG_NOISE = 2
ONE_NOISE = 3
TWO_NOISE = 4
LONG_NOISE = 5
BLACK_LIST_NOISE = 6
OUT_OF_SUBSET_NOISE = 7
SINGLE_CLUSTER = 8
